ansible_ssh_private_key_file: /home/matt/.ssh/id_ed25519
ansible_user: matt
concourse_fqdn: ci.ryuugu.dev
git_ansible_roles_branch: main
git_ansible_roles_repo: git@github.com:asdf57/ansible-roles.git
git_inventory_branch: main
git_inventory_repo: git@github.com:asdf57/inventory.git
git_provisioning_api_branch: main
git_provisioning_api_repo: git@github.com:asdf57/stigmergy.git
git_webhook_branch: main
git_webhook_repo: git@github.com:asdf57/webhook-server.git
host_data_path: /srv/homelab
nginx_ipv4: 10.0.2.123
openbao_api_fqdn: vault-api.ryuugu.dev
openbao_ipv4: 10.0.2.125
openbao_url: https://vault.ryuugu.dev
